<?php

/**
 * PluginS3ObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginS3ObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginS3ObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginS3Object');
    }
}